name: List targets
description: List targets
inputs:
  github_token:
    description: |
      GitHub Access Token
      pull-requests:write - Create pull request comments. Get pull requests
    required: false
    default: ${{ github.token }}
outputs:
  modules:
    description: list of changed modules
    value: ${{ steps.list-modules.outputs.modules }}

  targets:
    description: list of targets
    value: ${{ steps.list-targets.outputs.targets }}
runs:
  using: composite
  steps:
    - run: github-comment exec -- ci-info run | sed "s/^export //" >> "$GITHUB_ENV"
      shell: bash
      if: |
        ! contains(fromJSON('["workflow_dispatch", "schedule"]'), github.event_name)
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Check if the commit is latest
      shell: bash
      if: github.event_name == 'pull_request' || startsWith(github.event_name, 'pull_request_')
      run: |
        set -euo pipefail

        latest_head_sha=$(jq -r ".head.sha" $CI_INFO_TEMP_DIR/pr.json)
        if [ "$HEAD_SHA" != "$latest_head_sha" ]; then
          echo "::error::The head sha ($HEAD_SHA) isn't latest ($latest_head_sha)."
          exit 1
        fi
      env:
        HEAD_SHA: ${{github.event.pull_request.head.sha}}

    - run: go install github.com/hashicorp/terraform-config-inspect@latest
      shell: bash
    - uses: exoego/tfaction/list-working-dirs@update-module-use-site-2
      id: list-working-directory-configs
    - uses: exoego/tfaction/get-global-config@update-module-use-site-2
      id: global-config
    - uses: exoego/tfaction/list-module-callers@update-module-use-site-2
      id: list-module-callers
      if: "!fromJSON(steps.global-config.outputs.disable_update_local_path_module_caller)"
      with:
        config_files: ${{ steps.list-working-directory-configs.outputs.file }}
        module_files: ${{ steps.list-working-directory-configs.outputs.module_file }}
    - uses: exoego/tfaction/list-targets-with-changed-files@update-module-use-site-2
      id: list-targets
      with:
        changed_files: ${{ env.CI_INFO_TEMP_DIR }}/pr_all_filenames.txt
        labels: ${{ env.CI_INFO_TEMP_DIR }}/labels.txt
        pull_request: ${{ env.CI_INFO_TEMP_DIR }}/pr.json
        config_files: ${{ steps.list-working-directory-configs.outputs.file }}
        module_callers: ${{ steps.list-module-callers.outputs.file }}
    - uses: exoego/tfaction/list-changed-modules@update-module-use-site-2
      id: list-modules
      with:
        changed_files: ${{ env.CI_INFO_TEMP_DIR }}/pr_all_filenames.txt
        config_files: ${{ steps.list-working-directory-configs.outputs.module_file }}
