name: plan
description: plan
inputs:
  github_token:
    description: "GitHub Access Token"
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - uses: exoego/tfaction/terraform-plan@update-module-use-site-2
      if: env.TFACTION_JOB_TYPE == 'terraform'
      with:
        github_token: ${{inputs.github_token}}

    - uses: exoego/tfaction/tfmigrate-plan@update-module-use-site-2
      if: env.TFACTION_JOB_TYPE == 'tfmigrate'
      with:
        github_token: ${{inputs.github_token}}
